[package]
name = "fview"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
chrono_lc = "0.1.7"
clap = { version = "4.5.48", features = ["derive"] }
colored = "3.0.0"
walkdir = "2.5.0"
